/*
 Trabalho de Teoria dos Grafos
 Equipe: Antonio Celestino, Nathan Manera, Pedro Ferreira e Rafael Paiva
 Professor: Daves Martins
 4º Período BSI - IF Sudeste MG Juiz de Fora
 */
package grafosxml;

import com.mxgraph.model.mxCell;
import com.mxgraph.swing.mxGraphComponent;
import com.mxgraph.util.mxConstants;
import com.mxgraph.view.mxGraph;
import com.mxgraph.view.mxStylesheet;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Algoritmos extends javax.swing.JFrame {

    Grafo grafo;

    List<No> listaNos = new ArrayList<No>();
    List<Aresta> listaArestas = new ArrayList<Aresta>();
    String nomeAresta;
    String origemAresta;
    String destinoAresta;

    protected static mxGraph graph = new mxGraph();
    protected static HashMap m = new HashMap();
    private mxGraphComponent graphComponent;
    private mxCell cell = null;

    public static HashMap getM() {
        return m;
    }

    public static mxGraph getGraph() {
        return graph;
    }

    Object parent;

    public Algoritmos() {
        initComponents();
        setLocationRelativeTo(null); // deixa a janela no centro da tela

        parent = graph.getDefaultParent();
        graphComponent = new mxGraphComponent(graph);

        graphComponent.setPreferredSize(new Dimension(10, 10));
        graphComponent.setBackground(Color.WHITE);
        graphComponent.setComponentPopupMenu(popupMenu);
        jPanel1.add(graphComponent);

        graphComponent.getGraphControl().addMouseListener(new MouseAdapter() {
            public void mouseReleased(MouseEvent e) {
                cell = (mxCell) graphComponent.getCellAt(e.getX(), e.getY());
            }
        });
        getContentPane().setBackground(Color.white);

        graphComponent.validate();
        graphComponent.repaint();
        jPanel1.validate();
        jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        Remover = new javax.swing.JMenuItem();
        abc = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButtonLimparTela = new javax.swing.JButton();
        jBAbrirGrafo = new javax.swing.JButton();
        jTNomeGrafo = new javax.swing.JTextField();
        jBFechar = new javax.swing.JButton();
        jBDijkstra = new javax.swing.JButton();
        jBKruskal = new javax.swing.JButton();
        jBPrim = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });
        popupMenu.add(Remover);

        abc.setText("Cor");
        popupMenu.add(abc);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setComponentPopupMenu(popupMenu);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 10));

        jButtonLimparTela.setText("Limpar Tela");
        jButtonLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparTelaActionPerformed(evt);
            }
        });

        jBAbrirGrafo.setText("Abrir Grafo");
        jBAbrirGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirGrafoActionPerformed(evt);
            }
        });

        jTNomeGrafo.setEnabled(false);

        jBFechar.setText("Fechar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });

        jBDijkstra.setText("Dijkstra");
        jBDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDijkstraActionPerformed(evt);
            }
        });

        jBKruskal.setText("Kruskal");
        jBKruskal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKruskalActionPerformed(evt);
            }
        });

        jBPrim.setText("Prim");
        jBPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrimActionPerformed(evt);
            }
        });

        jButton4.setText("outro");

        jButton5.setText("outro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBAbrirGrafo)
                        .addGap(18, 18, 18)
                        .addComponent(jTNomeGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimparTela))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBDijkstra)
                        .addGap(18, 18, 18)
                        .addComponent(jBKruskal)
                        .addGap(18, 18, 18)
                        .addComponent(jBPrim)
                        .addGap(19, 19, 19)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAbrirGrafo)
                    .addComponent(jTNomeGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimparTela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBFechar)
                    .addComponent(jBDijkstra)
                    .addComponent(jBKruskal)
                    .addComponent(jBPrim)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(70, 70, 70))
        );

        setSize(new java.awt.Dimension(593, 492));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void jButtonLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparTelaActionPerformed
        graph.removeCells(graphComponent.getCells(new Rectangle(0, 0, graphComponent.getWidth(), graphComponent.getHeight())));
    }//GEN-LAST:event_jButtonLimparTelaActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        graphComponent.setPreferredSize(new Dimension(jPanel1.getWidth() - 10, jPanel1.getHeight() - 10));
        graphComponent.validate();
        graphComponent.repaint();
        jPanel1.validate();
        jPanel1.repaint();
    }//GEN-LAST:event_formWindowOpened

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        formWindowOpened(null);
    }//GEN-LAST:event_formComponentResized

    private void jBAbrirGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirGrafoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        File xmlFileLer = new File(fileChooser.getSelectedFile().getName());
        jTNomeGrafo.setText(fileChooser.getSelectedFile().getName().substring(0, fileChooser.getSelectedFile().getName().lastIndexOf(".")));
        XStream xstream = new XStream(new DomDriver());
        xstream.processAnnotations(Grafo.class);
        grafo = (Grafo) xstream.fromXML(xmlFileLer);
        grafo.geraMatriz();
        String xml = xstream.toXML(grafo);
        System.out.println(xml);
        listaNos.clear();
        listaArestas.clear();

        for (No n : grafo.getNos()) {
            listaNos.add(n);
        }
        for (Aresta a : grafo.getArestas()) {
            listaArestas.add(a);
        }
        grafo.setNos(listaNos);
        grafo.setArestas(listaArestas);
        grafo.mostraGrafoDesign(grafo);
    }//GEN-LAST:event_jBAbrirGrafoActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        graph.removeCells(graphComponent.getCells(new Rectangle(0, 0, graphComponent.getWidth(), graphComponent.getHeight())));
        setVisible(false);
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBKruskalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKruskalActionPerformed
        // PARTE 1: PEGA OS DADOS DO GRAFO ABERTO E CRIA UM NOVO GRAFO IDÊNTICO PARA SER MANIPULADO.
        String nome = "-kruskal";
        Grafo g = grafo.copiaGrafo(grafo, nome);   
        // PARTE 2: LIMPA A TELA.
        graph.removeCells(graphComponent.getCells(new Rectangle(0, 0, graphComponent.getWidth(), graphComponent.getHeight())));
        
        // PARTE 3: APLICA O ALGORITMO PARA ESCOLHER AS ARESTAS.
        
        
        // PARTE 4: VISUALIZA O NOVO GRAFO.
        g.mostraGrafoDesign(g);
        jTNomeGrafo.setText(g.getId());    
        // PARTE 5: SALVA O GRAFO EM XML.
        g.salvaGrafo(g);
    }//GEN-LAST:event_jBKruskalActionPerformed

    private void jBDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDijkstraActionPerformed
        // PARTE 1: PEGA OS DADOS DO GRAFO ABERTO E CRIA UM NOVO GRAFO IDÊNTICO PARA SER MANIPULADO.
        String nome = "-dijkstra";
        Grafo g = grafo.copiaGrafo(grafo, nome);   
        // PARTE 2: LIMPA A TELA.
        graph.removeCells(graphComponent.getCells(new Rectangle(0, 0, graphComponent.getWidth(), graphComponent.getHeight())));
        
        // PARTE 3: APLICA O ALGORITMO PARA ESCOLHER AS ARESTAS.
        
        
        // PARTE 4: VISUALIZA O NOVO GRAFO.
        g.mostraGrafoDesign(g);
        jTNomeGrafo.setText(g.getId());    
        // PARTE 5: SALVA O GRAFO EM XML.
        g.salvaGrafo(g);
    }//GEN-LAST:event_jBDijkstraActionPerformed

    private void jBPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrimActionPerformed
        // PARTE 1: PEGA OS DADOS DO GRAFO ABERTO E CRIA UM NOVO GRAFO IDÊNTICO PARA SER MANIPULADO.
        String nome = "-prim";
        Grafo g = grafo.copiaGrafo(grafo, nome);
        // PARTE 2: LIMPA A TELA.
        graph.removeCells(graphComponent.getCells(new Rectangle(0, 0, graphComponent.getWidth(), graphComponent.getHeight())));
        
        // PARTE 3: APLICA O ALGORITMO PARA ESCOLHER AS ARESTAS.
        List<Aresta> t = new ArrayList<Aresta>();                               //T: conjunto de arestas da árvore geradora mínima
        List<Aresta> arestasPossiveis = new ArrayList<Aresta>();                //AP: conjunto de arestas que se tornaram potenciais candidatas a entrarem conjunto T
        List<Aresta> arestasOriginais = new ArrayList<Aresta>(listaArestas);    //AO: conjunto de arestas do grafo original que ainda não se tornaram ou já viraram candidatas para entrarem no conjunto T
        List<No> v = new ArrayList<No>(listaNos);                               //V: conjunto de vértices do grafo original sem os vértices que já estão no conjunto B
        List<No> b = new ArrayList<No>();                                       //B: conjunto de vértices da árvore geradora mínima
        b.add(listaNos.get(0));
        v.remove(v.get(0));
        while(b.size() <= listaNos.size()){
            for (Aresta are : arestasOriginais) {   //esse 'for' procura as arestas do último vértice adicionado ao conjunto B
                if(are.getOrigem().equals(b.get(b.size()-1).getId()) || are.getDestino().equals(b.get(b.size()-1).getId())){ 
                    if(t.isEmpty()) {
                        arestasPossiveis.add(are);
                    } else {
                        for (No nov : v) {
                            if(nov.getId() == are.getOrigem()){
                                for (No nob : b) {
                                    if(nob.getId() == are.getDestino()){
                                        arestasPossiveis.add(are);
                                        break;
                                    }
                                }
                            }
                        }
                        for (No nov : v) {
                            if(nov.getId() == are.getDestino()){
                                for (No nob : b) {
                                    if(nob.getId() == are.getOrigem()){
                                        arestasPossiveis.add(are);
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            boolean bw = true;
            boolean bo = false;
            boolean bd = false;
            while(bw == true){                      //esse 'while' remove do conjunto AP e AO, as arestas que possuem ambos os vértices
                bw = false;                         //já incluídos no conjunto B, ou seja, remove do conjunto AP e AO as arestas que estão fechando circuito.
                for (Aresta aresPos : arestasPossiveis) {
                    String ao = aresPos.getOrigem();
                    String ad = aresPos.getDestino();
                    for (No no1 : b) {
                        if(no1.getId() == ao){
                            bo = true;
                            break;
                        }else{bw = false; bo = false;}
                    }
                    
                    for (No no2 : b) {
                        if(no2.getId() == ad){
                           bd = true;
                           break;
                        }else{bw = false; bd = false;}
                    }
                    
                    if(bo == true && bd == true){
                        arestasPossiveis.remove(aresPos);
                        bw = true;
                        for (Aresta a : arestasOriginais) {
                            if(aresPos.getNomeAresta() == a.getNomeAresta() && aresPos.getValorAresta() == a.getValorAresta() && aresPos.getOrigem() == a.getOrigem() && aresPos.getDestino() == a.getDestino()){
                                arestasOriginais.remove(a);
                                break;
                            }
                        }
                        break;
                    }else{bw = false; bo = false; bd = false;}
                }
                if(bw == false){break;}
            }
            
            if(arestasPossiveis.size() > 0){
                int valorMenor = parseInt(arestasPossiveis.get(0).getValorAresta());//esse trecho do algoritmo adiciona ao conjunto T a aresta do conjunto AP que tiver o menor getValorAresta()  
                for (Aresta aresPos : arestasPossiveis) {                           
                    if(parseInt(aresPos.getValorAresta()) < valorMenor){
                        valorMenor = parseInt(aresPos.getValorAresta());
                    }
                }
                for (Aresta aresPos : arestasPossiveis) {
                    if(parseInt(aresPos.getValorAresta()) == valorMenor){           //e quando adicionada ao conjunto T, é removida do conjunto AP e AO, pois já foi eleita aresta do conjunto T
                        t.add(new Aresta(aresPos.getNomeAresta(), aresPos.getValorAresta(), aresPos.getOrigem(), aresPos.getDestino()));
                        for (Aresta a : arestasPossiveis) {
                            if(aresPos.getNomeAresta() == a.getNomeAresta() && aresPos.getValorAresta() == a.getValorAresta() && aresPos.getOrigem() == a.getOrigem() && aresPos.getDestino() == a.getDestino()){
                                arestasPossiveis.remove(a);
                                break;
                            }
                        }
                        for (Aresta a : arestasOriginais) {
                            if(aresPos.getNomeAresta() == a.getNomeAresta() && aresPos.getValorAresta() == a.getValorAresta() && aresPos.getOrigem() == a.getOrigem() && aresPos.getDestino() == a.getDestino()){
                                arestasOriginais.remove(a);
                                break;
                            }
                        }
                        break;
                    }
                }
            }
            
            if(b.size() < listaNos.size()){                     //esse trecho do algoritmo adiciona ao conjunto B o vértice (um dos vértices da última aresta adicionada ao conjunto T) 
                String ao = t.get(t.size()-1).getOrigem();      //que está ainda no conjunto V, e depois de adicionar no conjunto B remove-o do conjunto V
                String ad = t.get(t.size()-1).getDestino();
                for (No nov : v) {
                    if(nov.getId() == ao){
                        for (No nob : b) {
                            if(nob.getId() == ad){
                                b.add(new No(ao));
                                v.remove(new No(ao));
                                break;
                            }
                        }
                        break;
                    }
                }
                for (No nov : v) {
                    if(nov.getId() == ad){
                        for (No nob : b) {
                            if(nob.getId() == ao){
                                b.add(new No(ad));
                                v.remove(new No(ad));
                                break;
                            }
                        }
                        break;
                    }
                }
            }else{
                break;  //quando todos os vértices do conjunto V estão no conjunto B o 'while' se encerra e depois é mostrado as arestas que foram para o conjunto T
            }
        }
        String T = "{";
        for (Aresta ares : t) {
            T += ares.getNomeAresta()+", ";
        }
        T += "}";
        g.getArestas().clear();
        g.setArestas(t);
        
        // PARTE 4: VISUALIZA O NOVO GRAFO.
        g.mostraGrafoDesign(g);
        jTNomeGrafo.setText(g.getId());
        JOptionPane.showMessageDialog(null, "Conjunto de arestas da árvore geradora mínima:\n"+T);
        // PARTE 5: SALVA O GRAFO EM XML.
        g.salvaGrafo(g);
    }//GEN-LAST:event_jBPrimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Algoritmos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Algoritmos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Algoritmos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Algoritmos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Algoritmos().setVisible(true);
            }
        });
//    
//        ViewHome frame = new ViewHome();
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.setSize(400, 320);
//        frame.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Remover;
    private javax.swing.JMenuItem abc;
    private javax.swing.JButton jBAbrirGrafo;
    private javax.swing.JButton jBDijkstra;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBKruskal;
    private javax.swing.JButton jBPrim;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonLimparTela;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTNomeGrafo;
    private javax.swing.JPopupMenu popupMenu;
    // End of variables declaration//GEN-END:variables
}
